version: '3'

services:

  app:
    build:
      context: .
      dockerfile: './Dockerfile'
    command: 'bash -c "source .env.docker && sh ./tools/wait-for-db.sh && ./gradlew run"'
    ports:
      - '80:8080'
    working_dir: '/app'
    links:
      - postgres
    volumes:
      - '.:/app'

  postgres:
    image: postgres:11
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres'
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: